### ISSUE TITLE
[1.0] First Release Checklist

### ISSUE THREAD

**Issue by CriticalFlaw** [CriticalFlaw/rayshud-Installer#1]
### Beta-1 Testing
- [x] Default Background tickbox string is too long, remove the word "menu" - Blazey on Steam (https://github.com/CriticalFlaw/rayshud-Installer/commit/84fd5693cf279fb9fd1b6e7bc7ddd67124d2c0af)
- [x] Changing the settings then doing the installation overwrites made changes - Blazey on Steam (https://github.com/CriticalFlaw/rayshud-Installer/commit/84fd5693cf279fb9fd1b6e7bc7ddd67124d2c0af)
- [x] Crosshair positioning is offset in-preview and in-game - Blazey on Steam (https://github.com/CriticalFlaw/rayshud-Installer/commit/628c0a69dc21b2edf2aabcae874b3f535a6c9fbe)
- [ ] Crosshair color reverted after play, possibly related to outlines - Blazey on Steam
- [ ] Open HUD Folder button doesn't always lead to the correct directory - Blazey on Steam

### User Interface
- [x] Implement a basic user-interface
- [x] Add a **Play Team Fortress 2** button
- [x] Add a **Open HUD Directory** button
- [x] Add a **Reset to Default** button
- [x] Add a label to indicate the current HUD status (Installed, Updated, Outdated etc.)
- [x] Add a label to indicate the last time installer-changes were applied
- [x] Add a label to indicate the installed and live rayshud versions
- [x] Implement a Crosshair Preview

### Installer Functionalities
- [x] Install/Remove
- [x] Update/Refresh
- [x] Retrieve and compare version numbers
- [x] Read/Write to a configuration file (JSON)
- [x] Restore user-settings if file is not found
- [x] Check for tf/custom/rayshud directory
- [x] Prompt user to provide the tf/custom directory

### Editor Functionalities
- [x] **Options**: HUD Version - Modern or Classic Main Menu
- [x] **Options**: Scoreboard - Normal or Minimal (6v6)
- [x] **Options**: Team Select - Left or Center
- [x] **Options**: Disguise Image - Enable or Disable
- [x] **Options**: Chat Position - Top or Bottom
- [x] **Options**: Default Background - Enable or Disable
- [x] **Ubercharge**: Animation - Flash, Solid or Rainbow, Toggle
- [x] **Ubercharge**: Bar Color - RGB values via Color Picker
- [x] **Ubercharge**: Solid Color - If uber-solid animation is enabled
- [x] **Ubercharge**: Flash Colors - If uber-flash animation is enabled
- [x] **Crosshair**: Style - BasicCross, CircleDot, Wings, ThinCross etc.
- [x] **Crosshair**: Enable - Enable or Disable
- [x] **Crosshair**: Outline - Enable or Disable
- [x] **Crosshair**: Pulse - Enable or Disable
- [x] **Crosshair**: Color - If crosshair is enabled
- [x] **Crosshair**: Pulse Color - If crosshair pulse is enabled
- [x] **Crosshair**: Size
- [x] **Options**: Healing Done Color
- [x] **Health**: Style - Default, TeamBar, Cross or Broesel
- [x] **Health**: Color Normal
- [x] **Health**: Color Buffed
- [x] **Health**: Color Low
- [x] **Ammo**: Clip Color
- [x] **Ammo**: Clip Color Low
- [x] **Ammo**: Reserve Color
- [x] **Ammo**: Reserve Color Low

### Extra Features/Changes
- [x] Automated error-reporting (Sentry.io)
- [x] Update the code-behind to use application settings
- [x] Refactor the crosshair controller to use a single node like KnuckleCrosses
- [ ] Self-update function (Potentially using [Squirrel](https://github.com/Squirrel/Squirrel.Windows))
- [ ] Add a progress bar, use threading to make the UI not freeze when installing
- [ ] Add KnuckleCrosses and KonrWings to the Crosshair options
- [x] Lower the target .NET Framework version for wider user compatibility (https://github.com/CriticalFlaw/rayshud-Installer/commit/919348fa2cdea6808224b9df2372fdb1bbc51a09)
- [ ] Continuous improvement of existing code, refactor where appropriate
- [ ] Update the user interface to be more user friendly and visually pleasing
   - [ ] Update the UI to use rayshud font Cerbetica
   - [ ] Migrate to Windows Presentation Foundation (WPF)
